image: python:latest

before_script:
  - apt-get update -q -y
  - apt-get install -y build-essential libgl1-mesa-glx kicad
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - pip install git+https://github.com/CadQuery/cadquery.git  # Comment out once there is a production release of CadQuery 2.x on PyPI

run:
  script:
    - ./generator.py --output_dir /tmp/3dmodels
    - find 3dmodels
    # - ./validator.py --unvalidated_dir /tmp/3dmodels --validated_dir /usr/share/kicad/3dmodels/ > audit_log.txt
    # - cat ./audit_log.txt
  when: manual
  timeout: 6 hours
  tags:
    - kicad-ubuntu20.04
